# AUTOGENERATED! DO NOT EDIT! File to edit: index.ipynb.

# %% auto 0
__all__ = ['learn_inf', 'categories', 'image', 'label', 'examples', 'intf', 'is_cat', 'classify_image']

# %% index.ipynb 2
from fastai.vision.all import *
import gradio as gr

def is_cat(x):
    return x[0].isupper()

# %% index.ipynb 18
learn_inf = load_learner(path/'export.pkl')

# %% index.ipynb 21
categories = ('cat', 'dog')

def classify_image(img):
    pred, _, probs = learn_inf.predict(img)
    return dict(zip(categories, map(float, probs)))

# %% index.ipynb 23
image = gr.inputs.Image(shape=(512, 512))
label = gr.outputs.Label()
examples = ['data/test/cats/cat_124.jpg', 'data/test/dogs/dog_177.jpg']

intf = gr.Interface(fn=classify_image,
                    inputs=image,
                    outputs=label,
                    examples=examples)
intf.launch(inline=False)
